### ISSUE TITLE
using trimmomatic on HPCh

### ISSUE THREAD

**Issue by henrick-aduda** [eanbit-rt2019/mini-projects#10]
Trying to use trimmomatic on the HPC but its a bit troublesome. Anyone with an idea on how to use trimmomatic on the hpc. 
This is what i tried out : 
`java -jar $TRIMMOJAR PE -phred33 \
    /home/user11/sampe1_read1.fastq.gz /home/user11/sample1_read2.fastq.gz \
    output_forward_paired.fq.gz output_forward_unpaired.fq.gz \
    output_reverse_paired.fq.gz output_reverse_unpaired.fq.gz \
    ILLUMINACLIP:../export/apps/trimmomatic/0.33/trimmomatic/adapters/TruSeq3-PE.fa:2:30:10 LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36
` @kipkurui

**Comment by kipkurui** [comment]
Hey @henrick-aduda, what is the error message you are encountering?

**Comment by henrick-aduda** [comment]
Hey @kipkurui i finally figured it out. we had a session on monday with Etienne and that shed some light on what was going on. Turns out i did not need to put in the directory to my input folders when running the trimmomatic command. Also i was running it earlier on the HPC  without module loading trimmomatic
